version: '3'
services:
   proxy:
     build: .
     networks:
        - wordpress
     ports:
        - "80:80"
        - "443:443"

networks:
  wordpress:
   external:  
    name: docker-compose_default
